- lib/action-ros2-ci.js
- src/action-ros2-ci.ts
Signed-off-by: Thomas Moulard <tmoulard@amazon.com>
> Select the correct branch when building

- lib/action-ros2-ci.js
- src/action-ros2-ci.ts
Signed-off-by: Thomas Moulard <tmoulard@amazon.com>
> Add support for PRs sent from a different repo

- lib/action-ros2-ci.js
- src/action-ros2-ci.ts
> Add colcon install bin dir to PATH to workaround ament_cmake issue

- .github/workflows/test.yml
> Upgrade workflow to run on MacOS-latest

- .github/workflows/test.yml
- action.yml
- dist/index.js
- src/action-ros2-ci.ts
This is useful to e.g. specify the build type.
> Add option to pass extra CMake flags

- dist/index.js
- package-lock.json
- package.json
husky will automatically ensure that the latest JS code is bundled with
each commit.
Note: only the `package.json` change is manually edited code, everything else is auto-generated.
> Add husky pre-commit hook

- action.yml
- dist/index.js
- src/action-ros-ci.ts
Re-submitting #83 after fixing the YAML syntax.
> Support for coverage-ignore-pattern input param (no default exclusion path)

- README.md
Change created in reference to issue https://github.com/ros-tooling/action-ros-ci/issues/31
> Reference action-ros-ci-template in README

- .github/workflows/test.yml
- README.md
> Bump setup-ros to 0.0.18

- .github/workflows/build-and-test.sh
- .github/workflows/test.yml
This refactors test.yml to always be using Docker on Linux.
It also uses matrix include feature to reduce duplication.
> Add codecov support

- .github/workflows/test.yml
- README.md
> Bump setup-ros to 0.0.22

- .github/workflows/test.yml
- README.md
> Bump setup-ros to 0.0.23

- .github/automerge.yml
Signed-off-by: Anas Abou Allaban <allabana@amazon.com>
> Add automerge action for dependabot

- README.md
Signed-off-by: Emerson Knapp <eknapp@amazon.com>
> Update README to mention required ros distributions

- .github/workflows/test.yml
> Add foxy support to the ROS2 package matrix

- .github/workflows/test.yml
> Only report if not a PR from a fork

- dist/index.js
- src/action-ros-ci.ts
Signed-off-by: Dan Rose <dan@digilabs.io>
> fix minor lint issue

- .eslintrc.json
- .github/dependabot.yml
- .github/workflows/autoapprove.yml
- .github/workflows/automerge.yml
- .github/workflows/test.yml
- .lintignore
- .lintstagedrc.js
- .prettierrc
- README.md
- __tests__/ros-ci.test.ts
- action.yml
- dist/index.js
- jest.config.js
- package-lock.json
- package.json
- tsconfig.json
* Set up fixup script so you can `npm run fixup` to fix simple lint and formatting issues.
* Expand scope of prettifying to all non-generated files.
* Make build/test ignore unstaged changes
> Add 'fixup' script and enhance precommit

- README.md
> Fix link in opening sentence of README.

- README.md
> Update README to use v0.2 instead of v0.1

- dist/index.js
- src/action-ros-ci.ts
The diff is complex because the code was formatted since there's now a bit more horizontal room.
> Extract main try/catch to separate function

- README.md
Closes #640
Follow-up to #642
This updates the README to point to Galactic.
Draft PR until Galactic is released.
> Update README to point to Galactic

- .github/workflows/test.yml
> Remove Kinetic test and add Noetic test

- dist/index.js
- src/action-ros-ci.ts
Closes #766
Alternative to #767
Since `rosdep` doesn't really work on Windows, trying to fix it is a bit useless. We can just not run `rosdep install` on Windows.
Signed-off-by: Christophe Bedard <christophe.bedard@apex.ai>
> Do not run 'rosdep install' on Windows

- .github/workflows/repo_file_for_test.repos
- .github/workflows/repo_file_for_test_dirs_with_same_name_as_repo.repos
See https://github.com/ament/ament_lint/pull/428
> Bump package versions in tests

- .github/workflows/test.yml
Remove Foxy and Melodic from tests, since they are now EOL, and add Iron.
> Update distros in tests

- dist/index.js
- src/action-ros-ci.ts
It should help identify incompatibility issues between different versions of some Python dependencies.
> Print list of Python packages and their version

- dist/index.js
- src/action-ros-ci.ts
> Use pip3 instead of pip

- README.md
* Add Jazzy wherever applicable
* Bump actions/checkout version
* Bump colcon-mixin-repository commit
> Update README to include Jazzy

- .github/workflows/test.yml
- README.md
- action.yml
- dist/index.js
- src/action-ros-ci.ts
> Add 'coverage-result' option to allow disabling coverage collection

- .github/workflows/test.yml
https://github.com/actions/setup-node/releases
> Update setup-node lib into test.yml
