lib/action-ros2-ci.js, src/action-ros2-ci.ts
rosdep cannot install dependencies for a subset of a workspace.
Add a line to remove the directories containing repositories
which are not dependend on.
Unfortunately, we need first to clone all repositories, so that
`colcon list` can resolve dependencies.
Signed-off-by: Thomas Moulard <tmoulard@amazon.com>
=> Speed-up CI by pruning unused dependencies

lib/action-ros2-ci.js, src/action-ros2-ci.ts
To use this GitHub action with e.g. rosbag2, we need
to remove the rosbag2 installed by the initial
`curl http:/... | vcs import src/`
This issue is only triggered when a package in ros2.repos
is the package under test.
=> Prune package under test from ros2.repos packages

lib/action-ros2-ci.js, src/action-ros2-ci.ts
Until this commit, action-ros2-ci.js was making the assumption that the
package under test, was also the repository directory name.
This is wrong for repositories containing more than one repo.
For instance, rosbag2 is the repository name, while ros2bag is a package
name in rosbag2.
This commit fixes this incorrect assumption, and enable this
action to work correctly with repositories containing more than
one package.
Testing:
See https://github.com/thomas-moulard/rosbag2/pull/1/checks?check_run_id=270924696
The action worked correctly. The package compilation failed, for
unrelated reasons.
=> Fix action-ros2-ci.ts to look for correct path

.github/workflows/test.yml, lib/action-ros2-ci.js, src/action-ros2-ci.ts
For now, always run lcov-result, independently of whether or not it is
a C++ package, to avoid overloading the user with too many flags.
Options to disable this behavior will be added down the road if
necessary.
This follows lcov-test-result tutorial: https://github.com/colcon/colcon-lcov-result
=> Compute C++ code coverage using colcon lcov-result

lib/action-ros2-ci.js, src/action-ros2-ci.ts
There was a logical error in the code. Instead of writing:
array1 = array1.concat(array2);
...to append array2 to array1. The code was:
array1.concat(array2);
...which does not do anything.
As a result, it was impossible to actually use a mixin.
=> Fix error when concatenating colcon build flags

.github/workflows/repo_file_for_test_cpp_package.repos, .github/workflows/test.yml, dist/index.js, src/action-ros2-ci.ts
Actually test the action output in the test workflow to detect failures.
Until now, many types of failures were not detected because the workflow
was only relying on the action failing without verifying whether the
final state of the worker is correct or not.
=> Add assertions to test workflow

.github/workflows/test.yml
There have been CI failures on PRs due to failures in checkout action ([example](https://github.com/ros-tooling/action-ros-ci/pull/88/checks?check_run_id=461359348#step:2:385)).
Bumping the checkout action to latest version might help fix that.
Signed-off-by: Prajakta Gokhale <prajaktg@amazon.com>
=> Update actions/checkout to latest version

dist/index.js, src/action-ros-ci.ts
This prevents logging weirdness if the exec promise is rejected.
Analogous to https://github.com/ros-tooling/setup-ros/pull/161
Signed-off-by: Dan Rose <dan@digilabs.io>
=> Remove extra level of async

.github/workflows/test.yml, dist/index.js, src/action-ros-ci.ts
Since `action-ros-ci` will commonly be used for building the repo that invokes it (and it generates a valid temporary `package.repo` file for use on-the-fly), there will be many cases where a custom full-blown `.repo` file will not be necessary. These cases should be fulfilled by passing in an empty string for the `vcs-repo-file-url`, which is what this pull request enables.
=> Allow vcs-repo-file-url to be empty

action.yml, dist/index.js, src/action-ros-ci.ts
This has uses, for instance, on Windows, where we need to
pass `--merge-install` in order to successfully build.  But
I can also see it as a safety-hatch to do arbitrary colcon
things in a pipeline.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
=> Add the ability to specify arbitrary colcon arguments.

README.md, dist/index.js, src/action-ros-ci.ts
[`colcon-coveragepy-result`](https://github.com/colcon/colcon-coveragepy-result) collects the Python coverage data for pure Python packages and for CMake packages with Python code (i.e. `ros.ament_cmake`, see https://github.com/ament/ament_cmake/pull/226) and combines it all into one file (`coveragepy/.coverage` relative to the workspace).
I also added an example to the README which uses the `coverage-pytest` mixin. This is both a `build` and a `test` mixin (for `ros.ament_cmake` packages and pure Python packages, respectively).
Part of #238
Requires https://github.com/ros-tooling/setup-ros/pull/208
Note: I'm not entirely sure why I have all these changes; I think I have the right packages/versions.
=> Run colcon-coveragepy-result to collect all Python coverage data

dist/index.js, src/action-ros-ci.ts
Resolve an issue introduced in #249 where the `--symlink-install` flag was added to all `colcon` verbs.
The flag is now only added to the `build` verb.
Signed-off-by: Anas Abou Allaban <allabana@amazon.com>
=> Add symlink install only to build command

.github/workflows/test.yml
Check out the correct ros2 sources for a given ROS 2 distribution when doing linter tests on this Action.
Part of solution for https://github.com/ros-tooling/aws-oncall/issues/139
Resolves failing builds for Dashing and Eloquent linting tests on this repository.
See this build https://github.com/ros-tooling/action-ros-ci/runs/870259660?check_suite_focus=true
This failure was revealed (but not caused) by https://github.com/ament/ament_lint/pull/241 - which used a Python 3.8 feature - showing us that we were checking out the latest version of ament_lint, instead of the distro-appropriate branches.
Signed-off-by: Emerson Knapp <eknapp@amazon.com>
=> Check out the correct ros2 sources for a given ROS 2 distribution

__tests__/ros-ci.test.ts
`action-ros-ci` for windows is slower than other tests.
Example run:
* https://github.com/ros-tooling/action-ros-ci/runs/870055757?check_suite_focus=true
The command is run but doesn't have enough time to complete before it times out.
=> Increase unit test timeout for slow Windows runs

README.md, action.yml, dist/index.js, src/action-ros-ci.ts
This adds a new `import-token` input to be used when importing a private repo. Otherwise the step fails with the following error on `vcs import`, since it tries to read a username and a password from stdin:
> `fatal: could not read Username for 'https://github.com': No such device or address`
The token is used in the HTTPS URL itself, e.g.: `https://[token@]github.com/user/repo.git`
Closes #224
Note that this doesn't use the approach suggested in #224. This is more of a simple workaround given the current logic.
=> Add import-token option to use with private repos

README.md
A job using action-ros-ci without that dependency installed [will fail](https://github.com/mikaelarguedas/sros2/runs/870838891?check_suite_focus=true):
```
/usr/bin/bash -c colcon coveragepy-result 				--packages-select sros2 sros2_cmake test_security
usage: colcon [-h] [--log-base LOG_BASE] [--log-level LOG_LEVEL]
{build,extension-points,extensions,graph,info,list,metadata,mixin,test,test-result,version-check}
...
colcon: error: argument verb_name: invalid choice: 'coveragepy-result' (choose from 'build', 'extension-points', 'extensions', 'graph', 'info', 'list', 'metadata', 'mixin', 'test', 'test-result', 'version-check')
##[error]The process '/usr/bin/bash' failed with exit code 2
```
Related to https://github.com/ros-tooling/action-ros-ci/issues/238#issuecomment-652025665
=> mark colcon-coveragepy-result as required dependency

.github/workflows/test.yml, __tests__/ros-ci.test.ts, dist/index.js, src/action-ros-ci.ts
* Pull argument name strings into constants 
* Clean up logic around distro validation and add more tests
* Add an e2e test for Ubuntu to build from source with no binary installation, which would have caught the shell script typo
Signed-off-by: Emerson Knapp <eknapp@amazon.com>
=> Fix messaging and logic from #278

.github/workflows/test.yml, dist/index.js, src/action-ros-ci.ts
This adds `rolling` to the list of valid ROS 2 distros. It allows users to develop & test against the latest source.
I've also added rolling to the `ros_distribution` list in the `test_ros2_from_source` test job.
Fixes #286
=> Add rolling to list of valid ROS 2 distros

.github/workflows/test.yml
This switches from 18.04 to 20.04 for Foxy tests. `ubuntu-latest` still refers to Ubuntu 18.04 Bionic. See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
I think the tests weren't failing because they were using very basic packages (`ament_copyright`/`ament_lint`) that don't have many system dependencies, so the odds of something breaking were probably quite low.
=> Run Foxy tests on Ubuntu Focal instead of Bionic

.github/workflows/repo_file_for_test_cpp_with_dependency.repos, .github/workflows/test.yml, dist/index.js, src/action-ros-ci.ts
Resolves #301
Instead of touching the file to ensure it exists before sourcing it - first check if the setup file exists and conditionally run the source command.
While refactoring this, remove the source command from all places where it's not needed.
=> Fix failure to touch /opt/ros/$DISTRO/setup.sh due to insufficient permissions

.prettierrc, dist/index.js
Prettier can infer the syntax from file extension. Forcing a parser only makes it crash when run, e.g. on a json file.
=> Remove "parser" from prettierrc

.github/workflows/test.yml
This is a more direct check, allowing future Windows versions and self-hosted runners
Signed-off-by: Dan Rose <dan@digilabs.io>
=> When detecting host os, use runner.os, not matrix.os

dist/index.js, package-lock.json, package.json
Switch from @zeit/ncc to @vercel/ncc as per author message:
https://www.npmjs.com/package/@zeit/ncc
Bring the following dependencies up to date:
- @typescript-eslint/eslint-plugin
- @typescript-eslint/parser
- @vercel/ncc
- eslint
- jest
- ts-jest
- typescript
Signed-off-by: Dan Rose <dan@digilabs.io>
=> Bump dependencies

.github/workflows/repo_file_for_test_dirs_with_same_name_as_repo.repos, .github/workflows/test.yml, dist/index.js, src/action-ros-ci.ts
Fixes https://github.com/ros-tooling/action-ros-ci/issues/342.
To fix the issue for my use-case, I had to introduce two patches:
1. Remove the vcs repository directory instead of any directory with the same name as the repository (892f4dd)
Use 'vcs diff' as a hack to list the root directories of repositories in the workspace, then cut the ' (git)' suffix, and grep for the repository name.
This should be a little more robust than the previous logic, which may accidentally remove parent and child directories that happen to have the same name as the repository being tested.
2. Add random string prefix to repository path in workspace (4be073c)
This is to avoid naming collisions when checking out the test repository.
Before: https://github.com/osrf/ros2_java/runs/1087011472
After: …
=> Handle workspace directories with same name as repository under test

.github/workflows/test.yml, README.md, package-lock.json, package.json
Fixes #429 - addPath deprecation error by updating dependencies.
Moves to minor version 1 in order to allow for better communicating API change vs patch fixes in the future (without committing to 1.0)
=> Update everything to 0.1.0 for release

.github/workflows/test.yml, README.md
=> Bump to setup-ros 0.1.0

.github/workflows/autoapprove.yml, .github/workflows/automerge.yml
Also disable the retry logic for automerge. Dependabot automatically updates its PRs, and the automerge is triggered on check_suite completion, so there is no reason to leave jobs up and spinning. These jobs have been tying up our limited action runners for the free tier, actually slowing down contributions.
=> Don't run dependabot automation jobs on non-dependabot PRs

DEVELOPING.md, README.md
Allows users to get patch-level bug fixes without having to constantly update patch versions in their repository.
Follows the example of https://github.com/actions/checkout
Reaching this decision by observing above official GitHub actions practice, and user case https://github.com/ros-controls/ros2_control/pull/253
=> Document new tag and release process for this action

src/action-ros-ci.ts
=> Include EOL distros in rosdep update - allows builds to continue working after EOL

dist/index.js, src/action-ros-ci.ts
The closing quotation mark was missing, but I think using a colon like this is cleaner.
=> Fix log message for bash commands

dist/index.js, package-lock.json, src/action-ros-ci.ts
Fixes #364
By adding the `-o pipefail` option to all bash commands, we can intercept failures properly, as in the following case when a bad package name is provided. This causes the workflow to exit at this point, rather than waiting all the way until `colcon build`
```
await execBashCommand(
`diff --new-line-format="" --unchanged-line-format="" <(colcon list -p) <(colcon list --packages-up-to ${packageNameList.join(
" "
)} -p) | xargs rm -rf`,
undefined,
options
);
```
=> Fail workflow at the first `colcon list` if a bad package name is specified

dist/index.js, src/action-ros-ci.ts
This prints a list of HEAD commits for all imported repos using `vcs log`.
It's especially useful when messing with/modifying the repos file(s). That's why I find it to be quite useful with ci.ros2.org, e.g. https://ci.ros2.org/job/ci_linux/13327/consoleFull#console-section-11. It's of course going to be useful after #157.
=> Print HEAD commits of all repos after import

dist/index.js, package-lock.json, package.json, src/action-ros-ci.ts
Signed-off-by: Snehal Bichkar <snehaldb@amazon.com>
Fixes issue: [429](https://issues.amazon.com/issues/DEVX-429)
Most of our github actions are flaky and hence cut on-call tickets on build failures. Most of the build fails because rosdep update fails to run because it cannot connect to the network. To resolve this issue this PR helps in adding retries to rosdep update
=> Added retry library for rosdep update

.github/CODEOWNERS
These reviews are noisy. One side-effect is that somebody changing only `package.json` for real will need to request reviews explicitly. This generally will only happen in version-bumps for release.
=> Set CODEOWNERS for package[-lock].json to @ghost so that dependabot reviews are not auto-assigned to humans

.eslintignore, .eslintrc.json, .github/workflows/test.yml, DEVELOPING.md, dist/index.js, package-lock.json, package.json, src/action-ros-ci.ts
Enforce linter style in the tests and note the autoformatting command in DEVELOPING.md.
Helps avoid the "please don't include formatting changes in functional PRs" comments. I think some people's editors, or maybe some pre-commit hook that I don't have is doing it for other developers.
Helps address comments on #523 and #524
Lint failure in first commit check https://github.com/ros-tooling/action-ros-ci/pull/535/checks?check_run_id=1884593227
=> Enforce prettier code styling

README.md, __tests__/ros-ci.test.ts, dist/index.js, src/action-ros-ci.ts, src/dependencies.ts
Relates to #157
Relates to #490
Similar to ci.ros2.org, this allows declaring PR dependencies by providing:
* repos file(s) to override the one(s) defined through the `vcs-repo-file-url` action input
* supplemental repos file(s) to be used along with the rest
This is done in a PR description, e.g.:
```
action-ros-ci-repos-override : https://gist.github.com/some-user/some.repos
action-ros-ci-repos-override : https://gist.github.com/some-user/some-other.repos
action-ros-ci-repos-supplemental : https://gist.github.com/some-user/some-supplemental.repos
action-ros-ci-repos-supplemental : file://path/to/some/other/supplemental.repos
```
but without the space before the colon (otherwise e2e tests for this PR will try to use those fake links).
To provide some feedback, lists of links of detected …
=> Support overriding repos files & providing supplemental ones in PRs

.github/workflows/test.yml, dist/index.js, src/action-ros-ci.ts
Fixes #518
By default, the `setup-ros` action does not install Connext DDS. However, when `action-ros-ci` runs `rosdep install` for a package that depends (directly or not) on `rmw_connext_cpp`, it tries to install `rti-connext-dds-5.3.1` from `apt`.
This fails because `DEBIAN_FRONTEND=noninteractive RTI_NC_LICENSE_ACCEPTED=yes` somehow doesn't work in accepting the Connext DDS license. In any case, I think we should avoid installing Connext DDS in `action-ros-ci` and have users use [`setup-ros`'s `install-connext` option](https://github.com/ros-tooling/setup-ros/blob/222a8c0740c8e8ddb93bcaf37ef482f4f4a3ac11/action.yml#L14-L18).
I've also added a test to catch this (in which case the test will take forever/times out), since the current tests use packages that do not actually depend on any …
=> Skip rti-connext-dds-5.3.1 when running rosdep install

.lintstagedrc.js
The pre-commit hook was failing because `.lintignore` doesn't exist anymore (since #535).
=> Fix lint commands in pre-commit hook

.eslintignore
eslint doesn't seem to handle yaml files correctly.
The `eslint --cache --fix` command in the pre-commit hook was failing when committing a change to a yaml file:
```
husky > pre-commit (node v12.21.0)
✔ Preparing...
⚠ Running tasks...
❯ Running tasks for *
✖ eslint --cache --fix [FAILED]
◼ prettier --write --ignore-unknown
◼ npm run build
◼ git add dist/index.js
◼ npm run test
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up...
✖ eslint --cache --fix:
/home/chris/action-ros-ci/action.yml
8:19  error  Parsing error: ';' expected
✖ 1 problem (1 error, 0 warnings)
husky > pre-commit hook failed (add --no-verify to bypass)
```
That doesn't really make sense. So let's just explicitly ignore yaml files for now.
=> Make eslint ignore yaml files

.lintstagedrc.js
Follow-up to #564
eslint does consider `.eslintignore` by default, but prettier does not (it uses `.prettierignore` instead). My bad.
Let's just roll back to explicitly providing the (right) file!
=> Explicitly provide .eslintignore to eslint & prettier

.github/workflows/test.yml, README.md, action.yml
Fixes #561
This changes the default value for the `vcs-repo-file-url` input to an empty
string. Therefore, by default, action-ros-ci will rely on binaries
(e.g. installed by setup-ros) for any dependencies.
=> Default to empty vcs-repo-file-url

.github/workflows/test.yml, README.md, action.yml, dist/index.js, src/action-ros-ci.ts
Relates to #525, #526, #555
This adds a `colcon-defaults` input. The JSON content is validated and then written to `~/.colcon/defaults.yaml`.
=> Add colcon-defaults input

README.md
This makes various small changes to the README:
* fix codecov example/snippet
* fixes #562
* codecov.yaml seems to have been renamed to codecov.yml
* actions/checkout is needed for codecov/codecov-action to get codecov.yml
* update/fix codecov.yml example
* mention needing to provide CODECOV_TOKEN only for private repos
* update codecov/codecov-action version
* use 'coverage-pytest' mixin in snippet too
* add table of contents for an easy overview of the README
* split ament_copyright basic example into binary vs source build
* this makes it obvious to users that there are 2 ways of using the action
* use a generic package name instead of ament_copyright
* uniformize snippets
* remove use of actions/checkout when not needed
* add `steps:` where needed so that snippets are complete-ish …
=> Update README and re-write some sections

dist/index.js, src/action-ros-ci.ts
It was originally added in #109 to avoid hardcoding the pytest coverage options. However, instead of using this option by default, users can simply use the `coverage-pytest` test mixin explicitly if they want to: https://github.com/colcon/colcon-mixin-repository/blob/1ddb69bedfd1f04c2f000e95452f7c24a4d6176b/coverage.mixin#L14
=> Remove --pytest-with-coverage option from default colcon test command

dist/index.js, src/action-ros-ci.ts
This adds the `--verbose` flag for `colcon lcov-result` (i.e. short coverage report for each package) and `--verbose --coverage-report-args -m` flags for `colcon coveragepy-result` (i.e. coverage report for each package and global coverage report, including uncovered lines).
The goal is to display generated coverage information (if any) directly in CI without *needing* to use services like codecov.
See:
* https://github.com/colcon/colcon-lcov-result#tips-and-tricks
* https://github.com/colcon/colcon-coveragepy-result#options
=> Use --verbose option for {lcov,coveragepy}-result

.github/workflows/test.yml
I often enable actions on my fork to open PRs (on my own fork) to test things out with CI. There's no real reason to run hourly scheduled jobs on forks.
I tried these and they didn't work:
* `if: ${{ (github.event_name != 'schedule') || (github.event_name == 'schedule' && !github.event.repository.fork) }}`
* `if: ${{ (github.event_name != 'schedule') || (github.event_name == 'schedule' && github.event.repository.fork == false) }}`
=> Don't run scheduled jobs on forks

dist/index.js, src/action-ros-ci.ts
Fixes #578
This makes sure that the paths returned by `vcs` are valid POSIX paths so that `rm -rf` works.
I tried for hours to use `sed` directly in the `execBashCommand()` call, but it never worked. It feels like something somewhere is messing up with the escape characters (it worked fine on Ubuntu).
=> Fix removal of duplicate repo on Windows

.github/workflows/test.yml, README.md, action.yml, dist/index.js, src/action-ros-ci.ts
This removes `colcon-mixin-name` and updates examples & tests to use `colcon-defaults` instead.
I also fixed some issues that I uncovered:
* `asan` mixin doesn't exist; `asan-gcc` does
* when setting `options.env`, you probably want to include `process.env`, otherwise the environment gets reset to nothing + whatever you provide with `options.env`; this was making runs that used `colcon-defaults` with C++ packages fail because cmake couldn't find any compiler
* for Docker jobs, `colcon` uses `/root/` as the home directory for some reason (you can see this when the action runs `colcon mixin update ...`), which isn't the same home directory that we use when deleting the `.colcon/` directory to clean up between jobs
=> Remove colcon-mixin-name

dist/index.js, src/action-ros-ci.ts
This is a minor fix that filters out empty elements when extracting an array of package names.
Before:
```yaml
with:
package-name: ament_copyright
```
It includes a space at the end:
```
Invoking: bash -c 'colcon build --event-handlers console_cohesion+ --packages-up-to ament_copyright   --symlink-install'
Invoking: bash -c 'colcon test --event-handlers console_cohesion+ --return-code-on-test-failure --packages-select ament_copyright '
```
Example:
```ts
let packageNames = `
package_a
package_b
`;
console.log(packageNames.split(RegExp("\\s")));
console.log(packageNames.split(RegExp("\\s")).join(" "));
console.log(packageNames.split(RegExp("\\s")).filter((v) => v.length > 0));
console.log(packageNames.split(RegExp("\\s")).filter((v) => v.length > 0).join(" "));
```
```
["", "package_a", …
```
=> Filter out empty elements for package names array

__tests__/ros-ci.test.ts, action.yml, dist/index.js, src/action-ros-ci.ts
Follow-up to #608, which didn't fix every occurrence.
=> Filter out empty elements when creating command strings

dist/index.js, src/action-ros-ci.ts
When running on `setup-ros-docker` images, there is no guarantee that `apt-get update` was run any time recently. When `setup-ros-docker` workflows were disabled for a little while (due to repository inactivity), this got so out of date that every user started failing because of out-of-date APT endpoints. We should have an expectation that the same code version should continue building on the same image, even if new images are not being created. This diff ensures that will be true.
=> Always update apt before installing rosdeps

.github/workflows/test.yml
Replaces https://github.com/ros-tooling/action-ros-ci/pull/607
=> Track v0.1 for setup-ros instead of specific patch version - more accurate to user experience

.github/dependabot.yml
It runs daily and basically kills the CI queue. For example, I've been trying to get #642 merged, but by the time CI has run, the branch is out of date, so I have to merge `master` into it, and then it goes to the end of the CI queue again. Rinse and repeat! :laughing:
We recommend pointing to a release instead of `master`, so there isn't much benefit to it running daily.
=> Make dependabot run weekly instead of daily

__tests__/ros-ci.test.ts, dist/index.js, src/action-ros-ci.ts
Part of https://github.com/ros-tooling/action-ros-ci/issues/640
This allows users to use `target-ros2-distro: galactic` (to use a Galactic binary installation). Note that users must currently use the testing repository to get Galactic binaries. See https://github.com/ros-tooling/setup-ros/pull/387
Users can still build Galactic from source until then.
=> Add galactic to valid distros list to support binary installs

.github/workflows/repo_file_for_test_private_repo.repos, .github/workflows/test.yml, dist/index.js, src/action-ros-ci.ts
Closes #270
This adds a test that uses `import-token` along with a repos file with a private repo.
It also switches to a different approach for using the `import-token` globally. This should hopefully fix all remaining private repo issues.
Supersedes #592 (see comments)
=> Fix import of external private repos and add private repo test

.github/dependabot.yml
setup-ros has been a lot less annoying, with this setup. applying here as well to reduce the noise in my notification feed
=> Run dependabot daily, but limit open PRs to reduce notification noise

.github/workflows/test.yml, dist/index.js
This updates the tests to remove Dashing & Eloquent from the config matrices and add Galactic instead.
=> Update distros in tests

.github/workflows/test.yml, README.md, action.yml, dist/index.js, src/action-ros-ci.ts
=> Test all packages in workspace by default

README.md, dist/index.js, src/action-ros-ci.ts
Replaces #328 (thanks @rotu for starting it)
`vcstool` can take URLs, we can simplify logic by using this instead of expecting curl installed, or configuring it with advanced options
=> Remove cURL in favor of using vcstool's ability to import URLs

.github/workflows/test.yml, README.md, action.yml, dist/index.js, src/action-ros-ci.ts
Closes #684
This adds a `skip-tests` option. When set to `true`, it skips tests and coverage data processing.
When the option is enabled, the action prints "Skipping tests" right after `colcon build`.
=> Add 'skip-tests' option

README.md, dist/index.js, src/action-ros-ci.ts
Resolves #691 
As @christophebedard has checked, added `x-access-token`.
https://github.com/ros-tooling/action-ros-ci/issues/691#issuecomment-889566873
Tested in my repository. (Changed to public after testing in private.)
https://github.com/kenji-miyake/action-ros-ci-test-private/pull/4
=> Add 'x-access-token:' to support GITHUB_TOKEN

dist/index.js, src/action-ros-ci.ts
Refinement of #697
In order to support dependencies with conditions like `<depend condition="$ROS_VERSION == 2">`, I added `ROS_VERSION` and `ROS_PYTHON_VERSION` in `install_rosdeps.sh`.
The followings are my test results.
|                                                               | Current Implementation                                                     | This PR                                                                                   |
| ------------------------------------------------------------- | -------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------- |
| 1. Docker Image                                               | :x: …
=> Add ROS environment variables to options

dist/index.js, src/action-ros-ci.ts
I found `action-ros-ci` will freeze when there are some interactive packages in dependencies.
https://github.com/kenji-miyake/grid_map/pull/1/checks?check_run_id=3324912225
So I added `DEBIAN_FRONTEND=noninteractive` in Linux and tested it below.
https://github.com/kenji-miyake/grid_map/pull/2/checks?check_run_id=3325170640
Note: This PR is based on #700. I will rebase this PR after #700 is merged.
=> Add DEBIAN_FRONTEND=noninteractive in Linux

.github/workflows/repo_file_for_test_cpp_package.repos, .github/workflows/test.yml, __tests__/ros-ci.test.ts, dist/index.js, src/action-ros-ci.ts
* run in cmd instead of bash
* disable colcon-lcov result
* use --merge-install as suggessted in ros2 docs
* disable colcon-test on windows
Windows Test and Test-Coverage functionality will be addressed in a future pr
Signed-off-by: Melvin Wang <melvin.mc.wang@gmail.com>
=> Fix Windows Build Functionality

.github/workflows/test.yml, README.md
See https://github.com/ros-tooling/action-ros-ci/pull/712#issuecomment-1029431530
=> Temporarily use windows-2019

.github/workflows/test.yml, README.md
=> Bump setup-ros to v0.3

.github/workflows/repo_file_for_test_cpp_package.repos, .github/workflows/test.yml, __tests__/ros-ci.test.ts, dist/index.js, src/action-ros-ci.ts
Closes #738
This adds support for Humble by adding it to the list of valid distros. I've updated the tests.
I didn't update the examples in the README since Humble has not yet been officially released, so users need to use the testing repository.
=> Add support for Humble

.github/workflows/test.yml, README.md
Follow-up to #741
Relates to #738
`setup-ros-docker` images for Humble were recently added: https://github.com/ros-tooling/setup-ros-docker/pull/51
=> Update tests and README after official Humble release

__tests__/ros-ci.test.ts, action.yml, dist/index.js, src/dependencies.ts
That is the new default, so follow it here.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
This is part of https://discourse.ros.org/t/change-default-branch-name-to-rolling-in-ros-2-core/26009/9
=> Rename the https://github.com/ros2/ros2 branch to 'rolling'.

.github/workflows/pr.yml, .github/workflows/test.yml
Copied from `setup-ros`: https://github.com/ros-tooling/setup-ros/blob/57bc9dc0ed672890441ae4fe26e55542b3920506/.github/workflows/pr.yml.
It's quite useful to make sure the `dist/index.js` file has been generated.
Signed-off-by: Christophe Bedard <christophe.bedard@apex.ai>
=> Move lint job to separate workflow file and check build artifact

dist/index.js, src/action-ros-ci.ts
PR to deal this [issue](https://github.com/ros-tooling/action-ros-ci/issues/782). This is a quick workaround to have both https and ssh urls be changed to use a PAT token.
=> Pull private submodules that use ssh urls

.github/workflows/test.yml
Support for Galactic ended after November 2022.
=> Remove Galactic since it is EOL

.github/workflows/build-and-test.sh, .github/workflows/pr.yml, .github/workflows/test.yml, DEVELOPING.md, action.yml, dist/index.js, package-lock.json, package.json, src/action-ros-ci.ts
Relates to https://github.com/ros-tooling/setup-ros/issues/519
Requires https://github.com/ros-tooling/setup-ros/pull/521
Closes #780
This also bumps versions of all dependencies. I had to work around a user permission/ID issue, see https://github.com/ros-tooling/setup-ros/pull/521#issuecomment-1427093726
Signed-off-by: Christophe Bedard <christophe.bedard@apex.ai>
=> Upgrade to Node.js v16

dist/index.js, src/action-ros-ci.ts
Closes #784
`action-ros-ci` currently runs `colcon test ...` with `--return-code-on-test-failure`, which makes the CI job fail right after that command if any tests fail. Users need to look through the test output to find the test failures, which is a bit annoying.
Instead, remove the `--return-code-on-test-failure` option from the `colcon test ...` command, and use `colcon test-result` instead. Run it first with the `--all` option so that all test results are printed, including the tests that passed. This allows quickly checking what tests ran. Since `colcon test-result` [returns a non-zero error code if any tests failed](https://github.com/colcon/colcon-test-result/blob/1e724a34231e337b0103ef56bca36417a335ed2d/colcon_test_result/verb/test_result.py#L109), ignore the return code here. …
=> Run 'colcon test-result' to print test failures

.github/workflows/test.yml, __tests__/ros-ci.test.ts, dist/index.js, package-lock.json, src/action-ros-ci.ts
=> Add Iron to valid distros

dist/index.js, src/action-ros-ci.ts
`action-ros-ci` currently uses `console_cohesion+` for both `colcon build` and `colcon test`. ci.ros2.org uses `console_cohesion+` for `colcon build` (prints output once package is done being processed) and `console_direct+` for `colcon test` (prints output directly).
Users can override the default event handler selected by `action-ros-ci` using the `extra-colcon-args` input (since those extra args are added on to the end of the `colcon test` call, and CLI arguments override any previous argument), but I think it makes sense to change the default event handler for `colcon test` to `console_direct+`.
=> Use console_direct event handler for colcon test

dist/index.js, src/action-ros-ci.ts
This PR replaces the hardcoded URL `https://github.com` with the content of the environment variable `GITHUB_SERVER_URL` in order to allow using this action on GitHub Enterprise instances. Fixes https://github.com/ros-tooling/action-ros-ci/issues/831.
=> read the GitHub server URL from the 'GITHUB_SERVER_URL' env variable

.github/workflows/test.yml, README.md, action.yml, dist/index.js, src/action-ros-ci.ts
Closes #829 
This PR adds an optional argument for skipping `rosdep install` in the action (`skip-rosdep-install`) and an optional argument to run `rosdep check` (`rosdep-check`), which only works if `skip-rosdep-install` is also enabled.
=> Add skip-rosdep-install & rosdep-check options

.github/workflows/repo_file_for_test_cpp_package.repos, .github/workflows/repo_file_for_test_dirs_with_same_name_as_repo_rolling.repos, .github/workflows/repo_file_for_test_rolling.repos, .github/workflows/test.yml
Requires https://github.com/ros-tooling/setup-ros/pull/658
See also https://github.com/ros-tooling/setup-ros-docker/pull/69
Note: the ubuntu-24.04 GitHub runner is not available yet: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners. I changed the workflow configs to use a Ubuntu Noble Docker image on top of ubuntu-latest. We could just keep this and not have to remove the workaround + bring it back for Ubuntu 26.04.
The `Test rosdep check/skip install options` CI job is failing, but I suspect that it is related to https://github.com/ros-tooling/setup-ros-docker/issues/67 and not these changes.
=> Add Ubuntu 24.04 Noble and switch Rolling to it

.github/dependabot.yml
Lower dependabot update frequency because we don't release _that_ frequently:
1. Ignore patch updates for npm dependencies
1. Set update interval to weekly, but don't limit the number of open PRs
=> Lower dependabot update frequency

.github/workflows/test.yml, README.md, action.yml, dist/index.js, src/action-ros-ci.ts
=> Add no-symlink-install option

dist/index.js, src/action-ros-ci.ts
args without space doesn't work after jazzy somehow.
```
root@f0e49ff535f9:/workspace/nav2_ws# colcon coveragepy-result --packages-select nav2_common --coverage-report-args -m
/usr/local/lib/python3.12/dist-packages/colcon_core/argument_parser/type_collector.py:9: UserWarning: 'colcon_core.argument_parser.type_collector.TypeCollectorDecorator' has been deprecated
class TypeCollectorDecorator(ArgumentParserDecorator):
/usr/local/lib/python3.12/dist-packages/colcon_core/argument_parser/type_collector.py:62: UserWarning: 'colcon_core.argument_parser.type_collector.SuppressTypeConversions' has been deprecated, use 'colcon_core.argument_parser.action_collector.SuppressTypeConversions' instead
class SuppressTypeConversions:
usage: colcon [-h] [--log-base LOG_BASE] [--log-level LOG_LEVEL] …
```
=> fix: add space before -m

dist/index.js, src/action-ros-ci.ts
Follow-up to #867 and #862
We cannot assume that `pip` is installed. This can happen when using `action-ros-ci`, but not `setup-ros` or the `setup-ros-docker`  images.
=> Make 'pip3 freeze' optional

dist/index.js, src/action-ros-ci.ts
See also https://github.com/ros-tooling/setup-ros/pull/694.
=> run either apt or dnf update with or without sudo

.github/dependabot.yml
Similar to https://github.com/ros-tooling/setup-ros/pull/724.
=> Ignore dependabot major version updates for @types/node

README.md, action.yml, dist/index.js, src/action-ros-ci.ts
Fixes #923
Make sure to use the current GitHub server URL when setting up authentication using `import-token` instead of using gitub.com.
=> Use GITHUB_SERVER_URL for authentication configuration

action.yml, dist/index.js, src/action-ros-ci.ts
=> Do not run `apt update` if `skipRosdepInstall==true`

dist/index.js, src/action-ros-ci.ts
Closes #954
This `|| true` after `rosdep install` has been in `action-ros-ci` since the very first implementation: https://github.com/ros-tooling/action-ros-ci/blame/b08ee66c5236c0e9df3b57a86f851e9ca66956af/src/action-ros2-ci.ts#L66-L72. The comment specifically says:
```
// For "latest" builds, rosdep often misses some keys, adding "|| true", to
// ignore those failures, as it is often non-critical.
```
This might not be a valid reason. After all, if some keys are missing, then some dependencies will be missing. Also, as laid out in #954, this hides actual errors reported by `rosdep` about dependencies declared in `package.xml` files.
=> Do not ignore 'rosdep install' failures/errors

.github/workflows/repo_file_for_test.repos, .github/workflows/repo_file_for_test_dirs_with_same_name_as_repo.repos, .github/workflows/repo_file_for_test_dirs_with_same_name_as_repo_noble.repos, .github/workflows/repo_file_for_test_noble.repos
Update the `ament_lint` pin to a non-broken version for `jazzy` and `rolling`
=> Fix Docker from Source CI

dist/index.js, src/action-ros-ci.ts
ROS 2 Rolling switched to version 7.3.0 (before Kilted): https://github.com/ros2/rmw_connextdds/pull/181.
This PR is similar to https://github.com/ros2/ros2_documentation/pull/5227. Just ignore the rosdep key for RTI Connext DDS 7.3.0. 
Relates to this `setup-ros` PR: https://github.com/ros-tooling/setup-ros/pull/798.
Relates a bit to https://github.com/ros2/ros2_documentation/issues/5226
=> Ignore rosdep key for new RTI Connext DDS 7.3.0 version

.github/workflows/test.yml
They are currently broken and it's no longer a Tier 1 platform. Let's get to green by disabling the builds for now, I do not think there are any resources to devote to fixing it at the moment.
=> Disable MacOS builds

.github/workflows/test.yml, README.md, dist/index.js, src/action-ros-ci.ts
See https://github.com/actions/runner-images/issues/12045
See the change to the VS path between 2019 and 2022:
1. 2019: https://github.com/actions/runner-images/blob/win19/20250113.1/images/windows/Windows2019-Readme.md#visual-studio-enterprise-2019
2. 2022: https://github.com/actions/runner-images/blob/releases/win22/20250623/images/windows/Windows2022-Readme.md#visual-studio-enterprise-2022
=> Use windows-2022 instead of -2019 due to deprecation

README.md
runs_on changed to runs-on
uses: ros-tooling/action-ros-ci@0.7
seems to not exist, changed to
ros-tooling/action-ros-ci@0.4.4
=> fix: typos in readme

action.yml, dist/index.js, src/action-ros-ci.ts
Hi dear maintainers,
I know that this action has been developed exclusively to be used on Github.
But other forges like [Forgejo](https://forgejo.org/) provide actions runners compatible with the Github ones.
I have been able to use your action on a private Forgejo instance but on my server, the SSH port of the Git server is not the default port 22. Hence my rosinstall files contains ssh urls with a specific port, in the format:
```
ssh://git@domain_name.com:port/org/repo.git
```
instead of the Github:
```
git@github.com:org/repo.git
```
By adding the `ssh-port` input for the action, I have managed to adapt the url replaced with the `insteaof` git config to make it work for my use-case.
Because the git url with a port has already a trailing `/` like on HTTPS urls, the config entry is the …
=> Add option to set ssh port for servers using non-standard SSH port
